The Nobel Prize has been among the most prestigious international awards since 1901. Each year, awards are bestowed in chemistry, literature, physics, physiology or medicine, economics, and peace. In addition to the honor, prestige, and substantial prize money, the recipient also gets a gold medal with an image of Alfred Nobel (1833 - 1896), who established the prize.

![](Nobel_Prize.png)

The Nobel Foundation has made a dataset available of all prize winners from the outset of the awards from 1901 to 2023. The dataset used in this project is from the Nobel Prize API and is available in the `nobel.csv` file in the `data` folder.

In this project, you'll get a chance to explore and answer several questions related to this prizewinning data. And we encourage you then to explore further questions that you're interested in!

# Project Instructions
## Analyze Nobel Prize winner data and identify patterns by answering the following questions:
1. What is the most commonly awarded gender and birth country? Storing the string answers as top_gender and top_country.
2. What decade had the highest proportion of US-born winners? Store this as an integer called max_decade_usa.
3. Who was the first woman to receive a Nobel Prize, and in what category? Save your string answers as first_woman_name and first_woman_category.
4. Which individuals or organizations have won multiple Nobel Prizes throughout the years? Store the full names in a list named repeat_list.

In [6]:
# Loading in required libraries
import pandas as pd
import seaborn as sns
import numpy as np
# Start coding here!

In [7]:
nobel = pd.read_csv("data/nobel.csv")

In [8]:
nobel.head()

   year    category  ... death_city death_country
0  1901   Chemistry  ...     Berlin       Germany
1  1901  Literature  ...   Châtenay        France
2  1901    Medicine  ...    Marburg       Germany
3  1901       Peace  ...     Heiden   Switzerland
4  1901       Peace  ...      Paris        France

[5 rows x 18 columns]

### Question 1: Most Commonly Awarded Gender and Birth Country

**Objective:** Identify the most commonly awarded gender and birth country.

**Solution:**
To determine the most common gender and birth country, we utilized the `value_counts()` method

In [21]:
top_gender = nobel['sex'].value_counts().index[0]
top_country = nobel['birth_country'].value_counts().index[0]

In [20]:
print("\n The gender with the most Nobel laureates is :", top_gender)
print(" The most common birth country of Nobel laureates is :", top_country)

 The gender with the most Nobel laureates is : Male
 The most common birth country of Nobel laureates is : United States of America

### Question 2: Decade with the Highest Proportion of US-Born Winners

**Objective:** Determine the decade with the highest proportion of US-born winners.

**Solution:**
We filtered data for US-born winners, transformed years to decades, and found the mode.

In [10]:
usa_data = nobel[nobel['birth_country'] == 'United States of America'][['birth_country','year']]
usa_data['year'] = usa_data['year'] / 10
max_decade_usa = int(usa_data['year'].round(0).value_counts().index[0]) * 10
max_decade_usa

2000

### Question 3: Decade and Category Pair with the Highest Proportion of Female Laureates

**Objective:** Identify the decade and category pair with the highest proportion of female laureates.

**Solution:**
We calculated the proportion of female laureates for each decade and category, then found the max.

In [11]:
nobel['decade'] = (np.floor(nobel['year'] /10) * 10 ).astype(int)
nobel['female_winner'] = nobel['sex'] == 'Female'
prop_female_winners = nobel.groupby(['decade' , 'category'] , as_index=False)['female_winner'].mean()
prop_female_winners

    decade    category  female_winner
0     1900   Chemistry       0.000000
1     1900  Literature       0.100000
2     1900    Medicine       0.000000
3     1900       Peace       0.071429
4     1900     Physics       0.076923
..     ...         ...            ...
67    2020   Economics       0.111111
68    2020  Literature       0.500000
69    2020    Medicine       0.125000
70    2020       Peace       0.285714
71    2020     Physics       0.166667

[72 rows x 3 columns]

In [12]:
max_female_decade_category = prop_female_winners[prop_female_winners['female_winner'] == prop_female_winners['female_winner'].max()][['decade' , 'category']]
max_female_decade_category

    decade    category
68    2020  Literature

In [13]:
max_female_dict = {max_female_decade_category.iloc[0 , 0] : max_female_decade_category.iloc[0 , 1]}
max_female_dict

{2020: 'Literature'}

### Question 4: First Woman to Receive a Nobel Prize and Category

**Objective:** Determine the first woman to receive a Nobel Prize and the corresponding category.

**Solution:**
We filtered data for female laureates, sorted by year, and extracted the first entry using the `sort_values()` method. The resulting variables hold the name and category of the first woman Nobel Prize winner.

In [14]:
woman_data = nobel[nobel['sex'] == 'Female'][['year', 'category' , 'full_name']].sort_values('year')
woman_data.head()

     year    category                                          full_name
19   1903     Physics                        Marie Curie, née Sklodowska
29   1905       Peace  Baroness Bertha Sophie Felicita von Suttner, n...
51   1909  Literature                      Selma Ottilia Lovisa Lagerlöf
62   1911   Chemistry                        Marie Curie, née Sklodowska
128  1926  Literature                                     Grazia Deledda

In [19]:
first_woman_name = str(woman_data.iloc[0 , 2])
first_woman_category = str(woman_data.iloc[0, 1])
print(f"\n The first woman to win a Nobel Prize was {first_woman_name}, in the category of {first_woman_category}.")

 The first woman to win a Nobel Prize was Marie Curie, née Sklodowska, in the category of Physics.

### Question 5: Individuals/Organizations with Multiple Nobel Prizes

**Objective:** Identify individuals or organizations that have won multiple Nobel Prizes.

**Solution:**
We grouped the data by organization and full name, counted occurrences, and extracted those with more than one prize.

In [18]:
counts = nobel['full_name'].value_counts()
repeats = counts[counts >= 2].index
repeat_list = list(repeats)
print("\n The repeat winners are :", repeat_list)

 The repeat winners are : ['Comité international de la Croix Rouge (International Committee of the Red Cross)', 'Linus Carl Pauling', 'John Bardeen', 'Frederick Sanger', 'Marie Curie, née Sklodowska', 'Office of the United Nations High Commissioner for Refugees (UNHCR)']