![Los Angeles skyline](la_skyline.jpg)

Los Angeles, California ðŸ˜Ž. The City of Angels. Tinseltown. The Entertainment Capital of the World! 

Known for its warm weather, palm trees, sprawling coastline, and Hollywood, along with producing some of the most iconic films and songs. However, as with any highly populated city, it isn't always glamorous and there can be a large volume of crime. That's where you can help!

You have been asked to support the Los Angeles Police Department (LAPD) by analyzing crime data to identify patterns in criminal behavior. They plan to use your insights to allocate resources effectively to tackle various crimes in different areas.

## The Data

They have provided you with a single dataset to use. A summary and preview are provided below.

It is a modified version of the original data, which is publicly available from Los Angeles Open Data.

# crimes.csv

| Column     | Description              |
|------------|--------------------------|
| `'DR_NO'` | Division of Records Number: Official file number made up of a 2-digit year, area ID, and 5 digits. |
| `'Date Rptd'` | Date reported - MM/DD/YYYY. |
| `'DATE OCC'` | Date of occurrence - MM/DD/YYYY. |
| `'TIME OCC'` | In 24-hour military time. |
| `'AREA NAME'` | The 21 Geographic Areas or Patrol Divisions are also given a name designation that references a landmark or the surrounding community that it is responsible for. For example, the 77th Street Division is located at the intersection of South Broadway and 77th Street, serving neighborhoods in South Los Angeles. |
| `'Crm Cd Desc'` | Indicates the crime committed. |
| `'Vict Age'` | Victim's age in years. |
| `'Vict Sex'` | Victim's sex: `F`: Female, `M`: Male, `X`: Unknown. |
| `'Vict Descent'` | Victim's descent:<ul><li>`A` - Other Asian</li><li>`B` - Black</li><li>`C` - Chinese</li><li>`D` - Cambodian</li><li>`F` - Filipino</li><li>`G` - Guamanian</li><li>`H` - Hispanic/Latin/Mexican</li><li>`I` - American Indian/Alaskan Native</li><li>`J` - Japanese</li><li>`K` - Korean</li><li>`L` - Laotian</li><li>`O` - Other</li><li>`P` - Pacific Islander</li><li>`S` - Samoan</li><li>`U` - Hawaiian</li><li>`V` - Vietnamese</li><li>`W` - White</li><li>`X` - Unknown</li><li>`Z` - Asian Indian</li> |
| `'Weapon Desc'` | Description of the weapon used (if applicable). |
| `'Status Desc'` | Crime status. |
| `'LOCATION'` | Street address of the crime. |

## Project Instructions
### Explore the crimes.csv dataset and use your findings to answer the following questions:
1. Which hour has the highest frequency of crimes? Store as an integer variable called peak_crime_hour. 
2. Which area has the largest frequency of night crimes (crimes committed between 10pm and 3:59am)? Save as a string variable called peak_night_crime_location
3. Identify the number of crimes committed against victims by age group (0-17, 18-25, 26-34, 35-44, 45-54, 55-64, 65+). Save as a pandas Series called victim_ages.

In [65]:
# Re-run this cell
#Â Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
crimes = pd.read_csv("crimes.csv", parse_dates=["Date Rptd", "DATE OCC"], dtype={"TIME OCC": str})
crimes.head()

       DR_NO  Date Rptd  ...  Status Desc                                  LOCATION
0  221412410 2022-06-15  ...  Invest Cont  13600    MARINA POINT                 DR
1  220314085 2022-07-22  ...  Invest Cont   2500 S  SYCAMORE                     AV
2  222013040 2022-08-06  ...  Invest Cont   3300    SAN MARINO                   ST
3  220614831 2022-08-18  ...  Invest Cont                         1900    TRANSIENT
4  231207725 2023-02-27  ...  Invest Cont   6200    4TH                          AV

[5 rows x 12 columns]

### Question 1: Identifying Peak Crime Hour

**Objective:** Determine the hour with the highest frequency of crimes and store the result as an integer variable called `peak_crime_hour`.

In [66]:
# Start coding here
# Use as many cells as you need
crimes['hour occ'] = np.floor(crimes['TIME OCC'].astype(int) / 100)

In [67]:
peak_crime_hour = int(crimes['hour occ'].value_counts().index[0])
peak_crime_hour

12

### Question 2: Identifying Area with the Largest Frequency of Night Crimes

**Objective:** Determine the area with the largest frequency of night crimes (committed between 10pm and 3:59am) and save the result as a string variable called `peak_night_crime_location`.

**Solution:**
We converted the 'TIME OCC' column to an integer format and created a new column, 'TIME OCC INT'. Then, we filtered crimes that occurred between 10pm and 3:59am and identified the area with the largest frequency of night crimes.

In [68]:
crimes['TIME OCC INT'] =crimes['TIME OCC'].astype(int)

In [69]:
peak_night_crime_location = crimes[(crimes['TIME OCC INT'] >= 2200) | (crimes['TIME OCC INT'] <=359)]['AREA NAME'].value_counts().index[0]
peak_night_crime_location

'Central'

In [70]:
crimes['Vict Age'].value_counts()

 0     62240
 30     5715
 35     5697
 32     5481
 31     5472
       ...
 95       25
 94       23
 97       22
 98       17
-2         7
Name: Vict Age, Length: 101, dtype: int64

### Question 3: Analyzing Crimes by Victim Age Groups

**Objective:** Identify the number of crimes committed against victims by age group (0-17, 18-25, 26-34, 35-44, 45-54, 55-64, 65+). Save the results as a pandas Series called `victim_ages`.

**Solution:**
We defined age bins and labels, then created a new column, 'age_group', using `pd.cut()` to bin victim ages into discrete intervals. The resulting Series, `victim_ages`, displays the frequency of crimes for each age group.

In [71]:
age_bins = [0, 17, 25, 34, 44, 54, 64, np.inf]
age_labels = ["0-17", "18-25", "26-34", "35-44", "45-54", "55-64", "65+"]

# Add a new column using pd.cut() to bin values into discrete intervals
crimes["age_group"] = pd.cut(crimes["Vict Age"],
                               bins=age_bins,
                               labels=age_labels)

# Find the category with the largest frequency
victim_ages = crimes["age_group"].value_counts()
victim_ages

26-34    47470
35-44    42157
45-54    28353
18-25    28291
55-64    20169
65+      14747
0-17      4528
Name: age_group, dtype: int64